name: Release
on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  semantic-release:
    environment: production
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: ${{ secrets.COMMIT_TOKEN }}
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 'lts/*'
      - name: Install semantic-release
        shell: bash
        run: npm install
      - name: Set up Python
        uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5.5.0
        with:
          python-version: '3.13'
      - name: Release
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.COMMIT_TOKEN }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: npx semantic-release
